"use client"

import { useState } from "react"
import { Mail, ExternalLink } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion"

const faqData = {
  title: "Frequently Asked Questions about Simulacrum",
  description:
    "Explore answers to common inquiries regarding Simulacrum's unique approach to simulating human experience, its plans, and platform features.",
  categories: [
    {
      categoryName: "Understanding Simulacrum",
      questions: [
        {
          q: "How does Simulacrum differ from standard AI writing or chatbot tools?",
          a: "Simulacrum isn't just about generating text; it's about simulating the internal monologue, emotional responses, and decision-making processes of defined personas within specific contexts. Our platform is built on a foundation of expertly curated 'rich impulsive data' to create authentic, immersive experiences that offer deep qualitative insights, going far beyond generic AI outputs.",
        },
        {
          q: "What kind of insights can I expect from using Simulacrum?",
          a: "You can expect to uncover the 'why' behind consumer behavior, identify unspoken pain points and motivations, test product or message resonance by simulating direct audience reactions, and understand the nuanced internal experiences of your target personas. It helps in areas like product validation, UX journey mapping, marketing message refinement, and even preparing for high-stakes presentations by simulating audience perception.",
        },
        {
          q: "Is Simulacrum difficult to learn and use?",
          a: "Simulacrum is designed with a user-friendly interface, particularly for market researchers, UX designers, and marketers. We provide pre-made personas and scenario templates to get you started quickly, along with a Pre-Simulation Guidance Layer to help you define your objectives effectively. While the insights are deep, the process of setting up and running a simulation is made intuitive.",
        },
      ],
    },
    {
      categoryName: "Plans & Subscription",
      questions: [
        {
          q: "Can I try Simulacrum before committing to a paid plan?",
          a: "Yes, we offer a free trial period (currently 'Free During Beta' for our MVP) that allows you to explore the core functionalities of Simulacrum and run a limited number of simulations.",
        },
        {
          q: "What happens if I need more simulations or features than my current plan offers?",
          a: "You can easily upgrade your plan at any time to access higher simulation volumes, more advanced features like the Custom Persona Builder or 'Arenas' Analysis, and increased collaboration capabilities. Our team can assist you in choosing the right plan for your evolving needs.",
        },
        {
          q: "Are there options for large teams or enterprise-level requirements?",
          a: "Absolutely. Our 'Architect' tier is designed for enterprises and offers custom pricing, personalized AI features, unlimited knowledge assets, advanced security, dedicated support, and API access (Roadmap). We work with you to tailor a solution that meets your organization's specific needs for deep human insight at scale.",
        },
        {
          q: "What forms of payment are accepted for subscriptions?",
          a: "We support major credit cards for our standard subscription plans. For Enterprise plans, we offer additional payment options, including invoicing, which can be discussed with our sales team.",
        },
        {
          q: "Is there a discount for annual subscriptions?",
          a: "Yes, we typically offer a discount of approximately 20% if you choose to subscribe to an annual plan instead of a monthly plan, providing significant savings for a longer-term commitment.",
        },
      ],
    },
    {
      categoryName: "Data, Privacy & Usage",
      questions: [
        {
          q: "How does Simulacrum handle the data I upload for scenarios or persona building?",
          a: "Your data is treated with the utmost confidentiality and security. Uploaded company knowledge, product details, marketing copy, and custom persona definitions are used solely to inform and contextualize your private simulations. We employ robust security measures, including encryption in transit and at rest. Specific details are outlined in our Privacy Policy and Terms of Service.",
        },
        {
          q: "Can I use the insights generated by Simulacrum for commercial purposes, including for my clients?",
          a: "Yes, the insights generated from your simulations are yours to use for your commercial purposes, including informing strategies for your clients, provided such use aligns with our Terms of Service and ethical guidelines. The platform is designed to empower businesses and researchers with actionable intelligence.",
        },
        {
          q: "Does Simulacrum use my simulation data to train its general AI models for other customers?",
          a: "No, Simulacrum does not use your specific, private simulation data or uploaded proprietary knowledge to train its general AI models for other customers. Our 'rich impulsive data' core is curated separately by our internal experts. We prioritize your data privacy and intellectual property. Enterprise clients may have options for custom, isolated model refinements using their own data, under specific agreements.",
        },
      ],
    },
  ],
  additionalHelp: {
    title: "Still have questions or need specialized assistance?",
    links: [
      { text: "Browse our Comprehensive Help Center", url: "#" },
      { text: "Email our Insight Success Team", email: "insights@simulacrum.ai" },
      { text: "Schedule a Personalized Consultation or Demo", url: "#" },
    ],
  },
}

function FAQ() {
  const [selectedCategory, setSelectedCategory] = useState(0)

  return (
    <section className="py-16 bg-gray-50">
      <div className="container mx-auto px-4 max-w-7xl">
        {/* Header */}
        <div className="text-center mb-16">
          <h2 className="text-4xl font-bold text-gray-900 mb-6">{faqData.title}</h2>
          <p className="text-xl text-gray-600 max-w-4xl mx-auto">{faqData.description}</p>
        </div>

        {/* FAQ Content */}
        <div className="grid lg:grid-cols-4 gap-8">
          {/* Category Navigation */}
          <div className="lg:col-span-1">
            <div className="sticky top-8">
              <h3 className="text-lg font-semibold text-gray-900 mb-4">Categories</h3>
              <nav className="space-y-2">
                {faqData.categories.map((category, index) => (
                  <button
                    key={index}
                    onClick={() => setSelectedCategory(index)}
                    className={`w-full text-left px-4 py-3 rounded-lg transition-colors ${
                      selectedCategory === index
                        ? "bg-purple-100 text-purple-700 font-medium"
                        : "text-gray-600 hover:bg-gray-100 hover:text-gray-900"
                    }`}
                  >
                    {category.categoryName}
                  </button>
                ))}
              </nav>
            </div>
          </div>

          {/* Questions */}
          <div className="lg:col-span-3">
            <Card className="bg-white shadow-sm">
              <CardContent className="p-0">
                <div className="p-6 border-b border-gray-200">
                  <h3 className="text-2xl font-bold text-gray-900">
                    {faqData.categories[selectedCategory].categoryName}
                  </h3>
                </div>

                <Accordion type="single" collapsible className="w-full">
                  {faqData.categories[selectedCategory].questions.map((item, index) => (
                    <AccordionItem
                      key={index}
                      value={`item-${index}`}
                      className="border-b border-gray-200 last:border-b-0"
                    >
                      <AccordionTrigger className="px-6 py-6 text-left hover:no-underline hover:bg-gray-50 transition-colors">
                        <span className="text-lg font-medium text-gray-900 pr-4">{item.q}</span>
                      </AccordionTrigger>
                      <AccordionContent className="px-6 pb-6">
                        <div className="text-gray-700 leading-relaxed">{item.a}</div>
                      </AccordionContent>
                    </AccordionItem>
                  ))}
                </Accordion>
              </CardContent>
            </Card>
          </div>
        </div>

        {/* Additional Help Section */}
        <div className="mt-16">
          <Card className="bg-gradient-to-r from-purple-50 to-blue-50 border-purple-200">
            <CardContent className="p-8 text-center">
              <h3 className="text-2xl font-bold text-gray-900 mb-4">{faqData.additionalHelp.title}</h3>
              <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
                {faqData.additionalHelp.links.map((link, index) => (
                  <div key={index}>
                    {link.email ? (
                      <Button
                        variant="outline"
                        className="border-purple-300 text-purple-700 hover:bg-purple-100"
                        asChild
                      >
                        <a href={`mailto:${link.email}`} className="flex items-center gap-2">
                          <Mail className="h-4 w-4" />
                          {link.text}
                        </a>
                      </Button>
                    ) : (
                      <Button
                        variant="outline"
                        className="border-purple-300 text-purple-700 hover:bg-purple-100"
                        asChild
                      >
                        <a href={link.url} className="flex items-center gap-2">
                          <ExternalLink className="h-4 w-4" />
                          {link.text}
                        </a>
                      </Button>
                    )}
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </section>
  )
}

export default FAQ
